# Scraping PriceCharting for the Pokémon card dataset

This notebook pulls Pokémon card prices from [pricecharting.com](https://www.pricecharting.com).

It does two things:

1. **Current prices** — for every set (e.g. `pokemon-promo`), walk the listing table
   and record each card's price at every grade (Ungraded, Grade 7/8/9/9.5, PSA 10).
2. **Price history** — for a card's product page, pull the monthly price-over-time
   series per grade (this is what powers the scrollytelling chart).

**Please scrape responsibly:** there's a polite delay between requests, retries with
backoff, and a normal browser User-Agent. The full dataset is ~300 sets and tens of
thousands of cards — start with a single set, confirm the output, then scale up.
Check PriceCharting's Terms of Service before running the whole thing.

### Setup

In [1]:
# !pip install requests beautifulsoup4 pandas lxml
import time, re, json, random
from datetime import datetime, timezone

import requests
import pandas as pd
from bs4 import BeautifulSoup

BASE = "https://www.pricecharting.com"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
}
DELAY = 1.5   # base seconds to wait between requests — keep this polite

session = requests.Session()
session.headers.update(HEADERS)


def fetch(url, method="GET", data=None, retries=3):
    """GET/POST with retry + backoff, then sleep so we don't hammer the server."""
    for attempt in range(retries):
        try:
            r = session.request(method, url, data=data, timeout=30)
            r.raise_for_status()
            time.sleep(DELAY + random.uniform(0, 0.6))
            return r.text
        except requests.RequestException as e:
            wait = 2 ** attempt
            print(f"  ! {e} -> retry in {wait}s")
            time.sleep(wait)
    raise RuntimeError(f"failed after {retries} tries: {url}")


def money(text):
    """'$2,800.00' -> 2800.0 ; blanks/dashes -> None."""
    if not text:
        return None
    t = text.replace("$", "").replace(",", "").strip()
    if t in ("", "-", "N/A"):
        return None
    try:
        return float(t)
    except ValueError:
        return None

### 1. Discover every Pokémon set\n\nThe category page links out to each set's `/console/pokemon-*` listing.

In [2]:
def discover_sets():
    html = fetch(f"{BASE}/category/pokemon-cards")
    slugs = sorted(set(re.findall(r"/console/(pokemon[a-z0-9-]+)", html)))
    print(f"found {len(slugs)} pokemon sets")
    return slugs

all_sets = discover_sets()
all_sets[:10]

found 299 pokemon sets

['pokemon-1999-topps-movie',
 'pokemon-1999-topps-tv',
 'pokemon-2000-topps-chrome',
 'pokemon-2000-topps-tv',
 'pokemon-2000-topps-tv-episode',
 'pokemon-2001-topps-johto',
 'pokemon-2001-topps-johto-sticker',
 'pokemon-2003-topps-advanced',
 'pokemon-2003-topps-advanced-die-cut',
 'pokemon-2004-starter-deck']

### 2. Scrape one set's current prices

Each listing lives in `table#games_table`. The visible grade columns vary by set,
so we read the `<thead>` labels and zip them onto each row's price cells. The
"more results" button is a POST form carrying a `cursor` — we follow it until the
last page.

In [3]:
def scrape_set(slug):
    url = f"{BASE}/console/{slug}"
    rows, labels, seen_cursors = [], None, set()
    data = None  # first request is a plain GET; later pages POST the cursor form

    while True:
        html = fetch(url, method="POST", data=data) if data else fetch(url)
        soup = BeautifulSoup(html, "lxml")
        table = soup.find("table", id="games_table")
        if table is None:
            break

        # grade column labels (drop the blank image column and the 'Card' column)
        if labels is None:
            ths = [th.get_text(strip=True) for th in table.select("thead th")]
            labels = [t for t in ths if t and t.lower() != "card"]

        new_rows = 0
        for tr in table.select('tbody tr[id^="product-"]'):
            a = tr.select_one("td.title a")
            if not a:
                continue
            href = a["href"]
            prices = [money(s.get_text(strip=True))
                      for s in tr.select("td.price span.js-price")]
            rec = {
                "set": slug,
                "product_id": tr.get("data-product"),
                "card": a.get_text(strip=True),
                "url": BASE + href if href.startswith("/") else href,
            }
            for label, price in zip(labels, prices):
                rec[label] = price
            rows.append(rec)
            new_rows += 1

        # follow pagination
        form = soup.select_one("form.js-next-page")
        cursor_inp = form.find("input", {"name": "cursor"}) if form else None
        if not cursor_inp or new_rows == 0:
            break
        cursor = cursor_inp.get("value")
        if cursor in seen_cursors:
            break
        seen_cursors.add(cursor)
        data = {inp.get("name"): inp.get("value", "")
                for inp in form.select("input")
                if inp.get("name") and inp.get("type") != "submit"}

    print(f"  {slug}: {len(rows)} cards")
    return rows

# quick test on the promo set the story uses
promo = scrape_set("pokemon-promo")
pd.DataFrame(promo).head()

  pokemon-promo: 2482 cards

,set,product_id,card,url,Ungraded,Grade 9,PSA 10
0,pokemon-promo,5834844,Pikachu with Grey Felt Hat #85,https://www.pricecharting.com/game/pokemon-pro...,922.00,974.00,2800.0
1,pokemon-promo,11197498,Mega Charizard X EX #23,https://www.pricecharting.com/game/pokemon-pro...,40.12,52.15,221.1
2,pokemon-promo,1958438,Ancient Mew,https://www.pricecharting.com/game/pokemon-pro...,112.50,251.69,2979.0
3,pokemon-promo,11239139,N's Zekrom #31,https://www.pricecharting.com/game/pokemon-pro...,12.30,43.51,476.5
4,pokemon-promo,4246447,Charizard VStar #SWSH262,https://www.pricecharting.com/game/pokemon-pro...,80.00,137.43,1675.0

### 3. Scrape all sets \u2192 `pokemon_prices.csv`\n\nStart small (`all_sets[:3]`) to sanity-check, then run the full list.

In [4]:
SETS_TO_SCRAPE = all_sets          # or a slice like all_sets[:3] to test
# SETS_TO_SCRAPE = ["pokemon-promo"]

all_rows = []
for i, slug in enumerate(SETS_TO_SCRAPE, 1):
    print(f"[{i}/{len(SETS_TO_SCRAPE)}] {slug}")
    try:
        all_rows += scrape_set(slug)
    except Exception as e:
        print(f"  !! skipped {slug}: {e}")

prices = pd.DataFrame(all_rows)
import os; os.makedirs("data", exist_ok=True)
prices.to_csv("data/pokemon_prices.csv", index=False)
print("saved data/pokemon_prices.csv", prices.shape)
prices.head()

[1/299] pokemon-1999-topps-movie
  pokemon-1999-topps-movie: 201 cards
[2/299] pokemon-1999-topps-tv
  pokemon-1999-topps-tv: 290 cards
[3/299] pokemon-2000-topps-chrome
  pokemon-2000-topps-chrome: 607 cards
[4/299] pokemon-2000-topps-tv
  pokemon-2000-topps-tv: 320 cards
[5/299] pokemon-2000-topps-tv-episode
  pokemon-2000-topps-tv-episode: 57 cards
[6/299] pokemon-2001-topps-johto
  pokemon-2001-topps-johto: 130 cards
[7/299] pokemon-2001-topps-johto-sticker
  pokemon-2001-topps-johto-sticker: 62 cards
[8/299] pokemon-2003-topps-advanced
  pokemon-2003-topps-advanced: 180 cards
[9/299] pokemon-2003-topps-advanced-die-cut
  pokemon-2003-topps-advanced-die-cut: 18 cards
[10/299] pokemon-2004-starter-deck
  pokemon-2004-starter-deck: 41 cards
[11/299] pokemon-2005-quick-construction-pack
  pokemon-2005-quick-construction-pack: 66 cards
[12/299] pokemon-2020-battle-academy
  pokemon-2020-battle-academy: 151 cards
[13/299] pokemon-ancient-origins
  pokemon-ancient-origins: 201 cards
[14/299] pokemon-aquapolis
  pokemon-aquapolis: 344 cards
[15/299] pokemon-arceus
  pokemon-arceus: 213 cards
[16/299] pokemon-ascended-heroes
  pokemon-ascended-heroes: 641 cards
[17/299] pokemon-astral-radiance
  pokemon-astral-radiance: 434 cards
[18/299] pokemon-base-set
  pokemon-base-set: 463 cards
[19/299] pokemon-base-set-2
  pokemon-base-set-2: 135 cards
[20/299] pokemon-battle-styles
  pokemon-battle-styles: 353 cards
[21/299] pokemon-best-of-game
  pokemon-best-of-game: 24 cards
[22/299] pokemon-black-
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-black- -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-black- -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-black- -> retry in 4s
  !! skipped pokemon-black-: failed after 3 tries: https://www.pricecharting.com/console/pokemon-black-
[23/299] pokemon-black-bolt
  pokemon-black-bolt: 435 cards
[24/299] pokemon-boundaries-crossed
  pokemon-boundaries-crossed: 296 cards
[25/299] pokemon-breakpoint
  pokemon-breakpoint: 248 cards
[26/299] pokemon-breakthrough
  pokemon-breakthrough: 328 cards
[27/299] pokemon-brilliant-stars
  pokemon-brilliant-stars: 426 cards
[28/299] pokemon-burger-king
  pokemon-burger-king: 158 cards
[29/299] pokemon-burning-shadows
  pokemon-burning-shadows: 321 cards
[30/299] pokemon-call-of-legends
  pokemon-call-of-legends: 212 cards
[31/299] pokemon-celebrations
  pokemon-celebrations: 135 cards
[32/299] pokemon-celestial-storm
  pokemon-celestial-storm: 342 cards
[33/299] pokemon-champion
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-champion -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-champion -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-champion -> retry in 4s
  !! skipped pokemon-champion: failed after 3 tries: https://www.pricecharting.com/console/pokemon-champion
[34/299] pokemon-chaos-rising
  pokemon-chaos-rising: 219 cards
[35/299] pokemon-chilling-reign
  pokemon-chilling-reign: 412 cards
[36/299] pokemon-chinese-151-collect
  pokemon-chinese-151-collect: 483 cards
[37/299] pokemon-chinese-cs4ac
  pokemon-chinese-cs4ac: 112 cards
[38/299] pokemon-chinese-cs4bc
  pokemon-chinese-cs4bc: 85 cards
[39/299] pokemon-chinese-cs5ac
  pokemon-chinese-cs5ac: 28 cards
[40/299] pokemon-chinese-csm2ac
  pokemon-chinese-csm2ac: 180 cards
[41/299] pokemon-chinese-csm2bc
  pokemon-chinese-csm2bc: 26 cards
[42/299] pokemon-chinese-csm2cc
  pokemon-chinese-csm2cc: 32 cards
[43/299] pokemon-chinese-csv4c
  pokemon-chinese-csv4c: 67 cards
[44/299] pokemon-chinese-csv5c
  pokemon-chinese-csv5c: 402 cards
[45/299] pokemon-chinese-csv9c
  pokemon-chinese-csv9c: 100 cards
[46/299] pokemon-chinese-gem-pack
  pokemon-chinese-gem-pack: 118 cards
[47/299] pokemon-chinese-gem-pack-2
  pokemon-chinese-gem-pack-2: 142 cards
[48/299] pokemon-chinese-gem-pack-3
  pokemon-chinese-gem-pack-3: 138 cards
[49/299] pokemon-chinese-gem-pack-4
  pokemon-chinese-gem-pack-4: 200 cards
[50/299] pokemon-chinese-gem-pack-5
  pokemon-chinese-gem-pack-5: 198 cards
[51/299] pokemon-chinese-promo
  pokemon-chinese-promo: 121 cards
[52/299] pokemon-cosmic-eclipse
  pokemon-cosmic-eclipse: 490 cards
[53/299] pokemon-crimson-invasion
  pokemon-crimson-invasion: 253 cards
[54/299] pokemon-crown-zenith
  pokemon-crown-zenith: 389 cards
[55/299] pokemon-crystal-guardians
  pokemon-crystal-guardians: 206 cards
[56/299] pokemon-dark-explorers
  pokemon-dark-explorers: 232 cards
[57/299] pokemon-darkness-ablaze
  pokemon-darkness-ablaze: 393 cards
[58/299] pokemon-delta-species
  pokemon-delta-species: 234 cards
[59/299] pokemon-deoxys
  pokemon-deoxys: 215 cards
[60/299] pokemon-destined-rivals
  pokemon-destined-rivals: 495 cards
[61/299] pokemon-detective-pikachu
  pokemon-detective-pikachu: 28 cards
[62/299] pokemon-diamond-
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-diamond- -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-diamond- -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-diamond- -> retry in 4s
  !! skipped pokemon-diamond-: failed after 3 tries: https://www.pricecharting.com/console/pokemon-diamond-
[63/299] pokemon-double-crisis
  pokemon-double-crisis: 68 cards
[64/299] pokemon-dragon
  pokemon-dragon: 196 cards
[65/299] pokemon-dragon-frontiers
  pokemon-dragon-frontiers: 199 cards
[66/299] pokemon-dragon-majesty
  pokemon-dragon-majesty: 146 cards
[67/299] pokemon-dragon-vault
  pokemon-dragon-vault: 34 cards
[68/299] pokemon-dragons-exalted
  pokemon-dragons-exalted: 250 cards
[69/299] pokemon-emerald
  pokemon-emerald: 213 cards
[70/299] pokemon-emerging-powers
  pokemon-emerging-powers: 207 cards
[71/299] pokemon-evolutions
  pokemon-evolutions: 244 cards
[72/299] pokemon-evolving-skies
  pokemon-evolving-skies: 440 cards
[73/299] pokemon-expedition
  pokemon-expedition: 340 cards
[74/299] pokemon-fates-collide
  pokemon-fates-collide: 249 cards
[75/299] pokemon-fire-red-
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-fire-red- -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-fire-red- -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-fire-red- -> retry in 4s
  !! skipped pokemon-fire-red-: failed after 3 tries: https://www.pricecharting.com/console/pokemon-fire-red-
[76/299] pokemon-flashfire
  pokemon-flashfire: 226 cards
[77/299] pokemon-forbidden-light
  pokemon-forbidden-light: 278 cards
[78/299] pokemon-fossil
  pokemon-fossil: 185 cards
[79/299] pokemon-furious-fists
  pokemon-furious-fists: 243 cards
[80/299] pokemon-fusion-strike
  pokemon-fusion-strike: 545 cards
[81/299] pokemon-generations
  pokemon-generations: 219 cards
[82/299] pokemon-go
  pokemon-go: 177 cards
[83/299] pokemon-great-encounters
  pokemon-great-encounters: 220 cards
[84/299] pokemon-guardians-rising
  pokemon-guardians-rising: 321 cards
[85/299] pokemon-gym-challenge
  pokemon-gym-challenge: 271 cards
[86/299] pokemon-gym-heroes
  pokemon-gym-heroes: 272 cards
[87/299] pokemon-heartgold-
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-heartgold- -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-heartgold- -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-heartgold- -> retry in 4s
  !! skipped pokemon-heartgold-: failed after 3 tries: https://www.pricecharting.com/console/pokemon-heartgold-
[88/299] pokemon-hidden-fates
  pokemon-hidden-fates: 249 cards
[89/299] pokemon-hidden-legends
  pokemon-hidden-legends: 205 cards
[90/299] pokemon-holon-phantoms
  pokemon-holon-phantoms: 220 cards
[91/299] pokemon-japanese-1996-carddass
  pokemon-japanese-1996-carddass: 309 cards
[92/299] pokemon-japanese-1997-carddass
  pokemon-japanese-1997-carddass: 166 cards
[93/299] pokemon-japanese-2002-mcdonald
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-2002-mcdonald -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-2002-mcdonald -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-2002-mcdonald -> retry in 4s
  !! skipped pokemon-japanese-2002-mcdonald: failed after 3 tries: https://www.pricecharting.com/console/pokemon-japanese-2002-mcdonald
[94/299] pokemon-japanese-20th-anniversary
  pokemon-japanese-20th-anniversary: 106 cards
[95/299] pokemon-japanese-25th-anniversary-collection
  pokemon-japanese-25th-anniversary-collection: 61 cards
[96/299] pokemon-japanese-25th-anniversary-promo
  pokemon-japanese-25th-anniversary-promo: 26 cards
[97/299] pokemon-japanese-abyss-eye
  pokemon-japanese-abyss-eye: 120 cards
[98/299] pokemon-japanese-advent-of-arceus
  pokemon-japanese-advent-of-arceus: 180 cards
[99/299] pokemon-japanese-alter-genesis
  pokemon-japanese-alter-genesis: 119 cards
[100/299] pokemon-japanese-ancient-roar
  pokemon-japanese-ancient-roar: 97 cards
[101/299] pokemon-japanese-awakening-legends
  pokemon-japanese-awakening-legends: 62 cards
[102/299] pokemon-japanese-awakening-psychic-king
  pokemon-japanese-awakening-psychic-king: 178 cards
[103/299] pokemon-japanese-bandit-ring
  pokemon-japanese-bandit-ring: 196 cards
[104/299] pokemon-japanese-battle-partners
  pokemon-japanese-battle-partners: 137 cards
[105/299] pokemon-japanese-battle-region
  pokemon-japanese-battle-region: 137 cards
[106/299] pokemon-japanese-best-of-xy
  pokemon-japanese-best-of-xy: 225 cards
[107/299] pokemon-japanese-black-bolt
  pokemon-japanese-black-bolt: 338 cards
[108/299] pokemon-japanese-blue-sky-stream
  pokemon-japanese-blue-sky-stream: 92 cards
[109/299] pokemon-japanese-cd-promo
  pokemon-japanese-cd-promo: 14 cards
[110/299] pokemon-japanese-challenge-from-the-darkness
  pokemon-japanese-challenge-from-the-darkness: 110 cards
[111/299] pokemon-japanese-classic-blastoise
  pokemon-japanese-classic-blastoise: 34 cards
[112/299] pokemon-japanese-classic-charizard
  pokemon-japanese-classic-charizard: 34 cards
[113/299] pokemon-japanese-clay-burst
  pokemon-japanese-clay-burst: 101 cards
[114/299] pokemon-japanese-crimson-haze
  pokemon-japanese-crimson-haze: 98 cards
[115/299] pokemon-japanese-crossing-the-ruins
  pokemon-japanese-crossing-the-ruins: 59 cards
[116/299] pokemon-japanese-cyber-judge
  pokemon-japanese-cyber-judge: 102 cards
[117/299] pokemon-japanese-dark-phantasma
  pokemon-japanese-dark-phantasma: 178 cards
[118/299] pokemon-japanese-darkness-and-to-light
  pokemon-japanese-darkness-and-to-light: 115 cards
[119/299] pokemon-japanese-double-blaze
  pokemon-japanese-double-blaze: 118 cards
[120/299] pokemon-japanese-dream-league
  pokemon-japanese-dream-league: 77 cards
[121/299] pokemon-japanese-dream-shine-collection
  pokemon-japanese-dream-shine-collection: 40 cards
[122/299] pokemon-japanese-eevee-heroes
  pokemon-japanese-eevee-heroes: 105 cards
[123/299] pokemon-japanese-emerald-break
  pokemon-japanese-emerald-break: 184 cards
[124/299] pokemon-japanese-ex-battle-boost
  pokemon-japanese-ex-battle-boost: 225 cards
[125/299] pokemon-japanese-expansion-pack
  pokemon-japanese-expansion-pack: 204 cards
[126/299] pokemon-japanese-expedition-expansion-pack
  pokemon-japanese-expedition-expansion-pack: 259 cards
[127/299] pokemon-japanese-fusion-arts
  pokemon-japanese-fusion-arts: 131 cards
[128/299] pokemon-japanese-future-flash
  pokemon-japanese-future-flash: 97 cards
[129/299] pokemon-japanese-gengar-vmax-high-class
  pokemon-japanese-gengar-vmax-high-class: 12 cards
[130/299] pokemon-japanese-glory-of-team-rocket
  pokemon-japanese-glory-of-team-rocket: 135 cards
[131/299] pokemon-japanese-go
  pokemon-japanese-go: 117 cards
[132/299] pokemon-japanese-gold-silver-new-world
  pokemon-japanese-gold-silver-new-world: 108 cards
[133/299] pokemon-japanese-golden-sky-silvery-ocean
  pokemon-japanese-golden-sky-silvery-ocean: 213 cards
[134/299] pokemon-japanese-gx-ultra-shiny
  pokemon-japanese-gx-ultra-shiny: 285 cards
[135/299] pokemon-japanese-heat-wave-arena
  pokemon-japanese-heat-wave-arena: 94 cards
[136/299] pokemon-japanese-holon-phantom
  pokemon-japanese-holon-phantom: 105 cards
[137/299] pokemon-japanese-holon-research
  pokemon-japanese-holon-research: 181 cards
[138/299] pokemon-japanese-incandescent-arcana
  pokemon-japanese-incandescent-arcana: 157 cards
[139/299] pokemon-japanese-inferno-x
  pokemon-japanese-inferno-x: 118 cards
[140/299] pokemon-japanese-intense-fight-in-the-destroyed-sky
  pokemon-japanese-intense-fight-in-the-destroyed-sky: 180 cards
[141/299] pokemon-japanese-jungle
  pokemon-japanese-jungle: 51 cards
[142/299] pokemon-japanese-leaders
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-leaders -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-leaders -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-leaders -> retry in 4s
  !! skipped pokemon-japanese-leaders: failed after 3 tries: https://www.pricecharting.com/console/pokemon-japanese-leaders
[143/299] pokemon-japanese-legendary-shine-collection
  pokemon-japanese-legendary-shine-collection: 29 cards
[144/299] pokemon-japanese-lost-abyss
  pokemon-japanese-lost-abyss: 129 cards
[145/299] pokemon-japanese-mask-of-change
  pokemon-japanese-mask-of-change: 136 cards
[146/299] pokemon-japanese-mega-brave
  pokemon-japanese-mega-brave: 96 cards
[147/299] pokemon-japanese-mega-dream-ex
  pokemon-japanese-mega-dream-ex: 489 cards
[148/299] pokemon-japanese-mega-starter-deck-gengar-ex
  pokemon-japanese-mega-starter-deck-gengar-ex: 24 cards
[149/299] pokemon-japanese-mega-symphonia
  pokemon-japanese-mega-symphonia: 95 cards
[150/299] pokemon-japanese-megalo-cannon
  pokemon-japanese-megalo-cannon: 174 cards
[151/299] pokemon-japanese-miracle-twins
  pokemon-japanese-miracle-twins: 117 cards
[152/299] pokemon-japanese-mysterious-mountains
  pokemon-japanese-mysterious-mountains: 184 cards
[153/299] pokemon-japanese-mystery-of-the-fossils
  pokemon-japanese-mystery-of-the-fossils: 50 cards
[154/299] pokemon-japanese-neo-premium-file
  pokemon-japanese-neo-premium-file: 30 cards
[155/299] pokemon-japanese-night-wanderer
  pokemon-japanese-night-wanderer: 97 cards
[156/299] pokemon-japanese-nihil-zero
  pokemon-japanese-nihil-zero: 120 cards
[157/299] pokemon-japanese-ninja-spinner
  pokemon-japanese-ninja-spinner: 122 cards
[158/299] pokemon-japanese-old-maid
  pokemon-japanese-old-maid: 42 cards
[159/299] pokemon-japanese-paradigm-trigger
  pokemon-japanese-paradigm-trigger: 128 cards
[160/299] pokemon-japanese-paradise-dragona
  pokemon-japanese-paradise-dragona: 96 cards
[161/299] pokemon-japanese-phantom-gate
  pokemon-japanese-phantom-gate: 196 cards
[162/299] pokemon-japanese-pokekyun-collection
  pokemon-japanese-pokekyun-collection: 34 cards
[163/299] pokemon-japanese-promo
  pokemon-japanese-promo: 1416 cards
[164/299] pokemon-japanese-raging-surf
  pokemon-japanese-raging-surf: 94 cards
[165/299] pokemon-japanese-remix-bout
  pokemon-japanese-remix-bout: 82 cards
[166/299] pokemon-japanese-rising-fist
  pokemon-japanese-rising-fist: 212 cards
[167/299] pokemon-japanese-rocket-gang
  pokemon-japanese-rocket-gang: 69 cards
[168/299] pokemon-japanese-rocket-gang-strikes-back
  pokemon-japanese-rocket-gang-strikes-back: 169 cards
[169/299] pokemon-japanese-ruler-of-the-black-flame
  pokemon-japanese-ruler-of-the-black-flame: 143 cards
[170/299] pokemon-japanese-scarlet-
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-scarlet- -> retry in 1s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-scarlet- -> retry in 2s
  ! 404 Client Error: Not Found for url: https://www.pricecharting.com/console/pokemon-japanese-scarlet- -> retry in 4s
  !! skipped pokemon-japanese-scarlet-: failed after 3 tries: https://www.pricecharting.com/console/pokemon-japanese-scarlet-
[171/299] pokemon-japanese-scarlet-ex
  pokemon-japanese-scarlet-ex: 110 cards
[172/299] pokemon-japanese-secret-of-the-lakes
  pokemon-japanese-secret-of-the-lakes: 251 cards
[173/299] pokemon-japanese-shining-darkness
  pokemon-japanese-shining-darkness: 226 cards
[174/299] pokemon-japanese-shining-legends
  pokemon-japanese-shining-legends: 84 cards
[175/299] pokemon-japanese-shiny-star-v
  pokemon-japanese-shiny-star-v: 340 cards
[176/299] pokemon-japanese-shiny-treasure-ex
  pokemon-japanese-shiny-treasure-ex: 486 cards
[177/299] pokemon-japanese-sky-legend
  pokemon-japanese-sky-legend: 71 cards
[178/299] pokemon-japanese-snow-hazard
  pokemon-japanese-snow-hazard: 102 cards
[179/299] pokemon-japanese-southern-islands
  pokemon-japanese-southern-islands: 22 cards
[180/299] pokemon-japanese-space-time
  pokemon-japanese-space-time: 235 cards
[181/299] pokemon-japanese-split-earth
  pokemon-japanese-split-earth: 185 cards
[182/299] pokemon-japanese-star-birth
  pokemon-japanese-star-birth: 129 cards
[183/299] pokemon-japanese-start-deck-100
  pokemon-japanese-start-deck-100: 422 cards
[184/299] pokemon-japanese-start-deck-100-battle-collection
  pokemon-japanese-start-deck-100-battle-collection: 1533 cards
[185/299] pokemon-japanese-stellar-miracle
  pokemon-japanese-stellar-miracle: 137 cards
[186/299] pokemon-japanese-super-electric-breaker
  pokemon-japanese-super-electric-breaker: 140 cards
[187/299] pokemon-japanese-svg-special-set
  pokemon-japanese-svg-special-set: 7 cards
[188/299] pokemon-japanese-tag-all-stars
  pokemon-japanese-tag-all-stars: 362 cards
[189/299] pokemon-japanese-tag-bolt
  pokemon-japanese-tag-bolt: 121 cards
[190/299] pokemon-japanese-taruka
  pokemon-japanese-taruka: 45 cards
[191/299] pokemon-japanese-terastal-festival
  pokemon-japanese-terastal-festival: 485 cards
[192/299] pokemon-japanese-the-town-on-no-map
  pokemon-japanese-the-town-on-no-map: 186 cards
[193/299] pokemon-japanese-topsun
  pokemon-japanese-topsun: 390 cards
[194/299] pokemon-japanese-triplet-beat
  pokemon-japanese-triplet-beat: 105 cards
[195/299] pokemon-japanese-vending
  pokemon-japanese-vending: 154 cards
[196/299] pokemon-japanese-violet-ex
  pokemon-japanese-violet-ex: 110 cards
[197/299] pokemon-japanese-vmax-climax
  pokemon-japanese-vmax-climax: 341 cards
[198/299] pokemon-japanese-vs
  pokemon-japanese-vs: 169 cards
[199/299] pokemon-japanese-vstar-universe
  pokemon-japanese-vstar-universe: 355 cards
[200/299] pokemon-japanese-web
  pokemon-japanese-web: 96 cards
[201/299] pokemon-japanese-white-flare
  pokemon-japanese-white-flare: 331 cards
[202/299] pokemon-japanese-wild-blaze
  pokemon-japanese-wild-blaze: 181 cards
[203/299] pokemon-japanese-wild-force
  pokemon-japanese-wild-force: 102 cards
[204/299] pokemon-japanese-wind-from-the-sea
  pokemon-japanese-wind-from-the-sea: 183 cards
[205/299] pokemon-japanese-world-champions-pack
  pokemon-japanese-world-champions-pack: 213 cards
[206/299] pokemon-japanese-yamabuki-city-gym
  pokemon-japanese-yamabuki-city-gym: 33 cards
[207/299] pokemon-journey-together
  pokemon-journey-together: 411 cards
[208/299] pokemon-jungle
  pokemon-jungle: 159 cards
[209/299] pokemon-korean-eevee-heroes
  pokemon-korean-eevee-heroes: 108 cards
[210/299] pokemon-korean-electric-breaker
  pokemon-korean-electric-breaker: 140 cards
[211/299] pokemon-korean-glory-of-team-rocket
  pokemon-korean-glory-of-team-rocket: 134 cards
[212/299] pokemon-korean-promo

,set,product_id,card,url,Ungraded,Grade 9,PSA 10
0,pokemon-1999-topps-movie,6777795,Ready For Battle,https://www.pricecharting.com/game/pokemon-199...,1416.85,NaN,NaN
1,pokemon-1999-topps-movie,3560907,Playtime [Corrected Foil] #57,https://www.pricecharting.com/game/pokemon-199...,NaN,NaN,NaN
2,pokemon-1999-topps-movie,3560860,Togepi in Trouble [Corrected] #45,https://www.pricecharting.com/game/pokemon-199...,NaN,NaN,NaN
3,pokemon-1999-topps-movie,3560886,Everyone Pull [Corrected Foil] #52,https://www.pricecharting.com/game/pokemon-199...,NaN,NaN,NaN
4,pokemon-1999-topps-movie,3560856,Looks Like Trouble [Corrected] #44,https://www.pricecharting.com/game/pokemon-199...,NaN,NaN,NaN

### 4. Price history per card \u2192 `pokemon_price_history.csv`

Each product page embeds `VGPC.chart_data`: monthly `[timestamp_ms, price_in_cents]`
points for six internal series. The series keys don't match their labels, so this
is the verified mapping (a `0` means "no sale that month" and is skipped).

In [5]:
# product-page series key -> the grade it actually represents
GRADE_TO_SERIES = {
    "Ungraded":  "used",
    "Grade 7":   "cib",
    "Grade 8":   "new",
    "Grade 9":   "graded",
    "Grade 9.5": "boxonly",
    "PSA 10":    "manualonly",
}

def scrape_history(product_url):
    html = fetch(product_url)
    m = re.search(r"VGPC\.chart_data\s*=\s*(\{.*?\})\s*;", html, re.S)
    if not m:
        return []
    chart = json.loads(m.group(1))
    out = []
    for grade, key in GRADE_TO_SERIES.items():
        for ts, cents in chart.get(key, []):
            if not cents:            # 0 = no data that month
                continue
            date = datetime.fromtimestamp(ts / 1000, tz=timezone.utc).strftime("%Y-%m-%d")
            out.append({"grade": grade, "date": date, "price": cents / 100.0})
    return out

# test on a single card
scrape_history("https://www.pricecharting.com/game/pokemon-promo/pikachu-with-grey-felt-hat-85")[:5]

[{'grade': 'Ungraded', 'date': '2023-09-01', 'price': 119.0},
 {'grade': 'Ungraded', 'date': '2023-10-01', 'price': 122.46},
 {'grade': 'Ungraded', 'date': '2023-11-01', 'price': 152.0},
 {'grade': 'Ungraded', 'date': '2023-12-01', 'price': 139.08},
 {'grade': 'Ungraded', 'date': '2024-01-01', 'price': 129.02}]

**Heads up:** history is one request per card, so the full dataset is tens of
thousands of requests. Test on a small slice first.

In [6]:
subset = prices.head(20)          # <-- start small; raise once you're happy

history = []
for i, row in enumerate(subset.itertuples(index=False), 1):
    print(f"[{i}/{len(subset)}] {row.card}")
    try:
        recs = scrape_history(row.url)
        for r in recs:
            r.update(card=row.card, set=row.set, product_id=row.product_id)
        history += recs
    except Exception as e:
        print("  !!", e)

hist_df = pd.DataFrame(history)
import os; os.makedirs("data", exist_ok=True)
hist_df.to_csv("data/pokemon_price_history.csv", index=False)
print("saved data/pokemon_price_history.csv", hist_df.shape)
hist_df.head()

[1/20] Ready For Battle
[2/20] Playtime [Corrected Foil] #57
[3/20] Togepi in Trouble [Corrected] #45
[4/20] Everyone Pull [Corrected Foil] #52
[5/20] Looks Like Trouble [Corrected] #44
[6/20] Better Than Ever [Corrected] #56
[7/20] Everyone Pull [Corrected] #52
[8/20] C'Mon We Need Help [Rainbow Foil] #59
[9/20] First Movie Booster Pack
[10/20] Pikachu's Vacation #42
[11/20] Booster Box
[12/20] Legends #1
[13/20] Trapped Charizard #51
[14/20] Farewell #39
[15/20] The Tail  End of the Race #50
[16/20] Fight Rages #35
[17/20] A Great Day [Corrected] #58
[18/20] Mechanical Mewtwo [Rainbow Foil] #6
[19/20] Future Looks Bright #41
[20/20] Trapped Charizard [Rainbow Foil] #51
saved pokemon_price_history.csv (2176, 6)

,grade,date,price,card,set,product_id
0,Ungraded,2025-08-01,1882.0,Ready For Battle,pokemon-1999-topps-movie,6777795
1,Ungraded,2025-09-01,1882.0,Ready For Battle,pokemon-1999-topps-movie,6777795
2,Ungraded,2025-10-01,1882.0,Ready For Battle,pokemon-1999-topps-movie,6777795
3,Ungraded,2025-12-01,1882.0,Ready For Battle,pokemon-1999-topps-movie,6777795
4,Ungraded,2026-01-01,1882.0,Ready For Battle,pokemon-1999-topps-movie,6777795